### ISSUE TITLE
Start checking for bluetooth state changed with '.bluetoothStateChanged().listen' throws an error

### ISSUE THREAD

**Issue by dkozenkov** [Lukangi/beacon_scanner#1]
When I call the 'BeaconScanner.instance.bluetoothStateChanged().listen', an errors appears:

```
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at com.lukangagames.plugins.beaconscanner.FlutterBluetoothStateReceiver.onListen(Unknown Source:2)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at android.os.Handler.handleCallback(Handler.java:938)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at android.os.Looper.loopOnce(Looper.java:226)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at android.os.Looper.loop(Looper.java:313)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at android.app.ActivityThread.main(ActivityThread.java:8751)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/EventChannel#beacon_scanner_bluetooth_state_changed(22347): 	at com.android.internal.os.ZygoteInit.man(ZygoteInit.java:1135)

════════ Exception caught by services library ══════════════════════════════════
The following PlatformException was thrown while activating platform stream on channel beacon_scanner_bluetooth_state_changed:
PlatformException(error, Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter o, null, null)

When the exception was thrown, this was the stack
#0      StandardMethodCodec.decodeEnvelope
message_codecs.dart:652
#1      MethodChannel._invokeMethod
platform_channel.dart:310
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure>
platform_channel.dart:652
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════
```

**Comment by Lukangi** [comment]
Thank you for your bug report.
It should be fixed in version 0.0.4.
